#!/usr/bin/env python3
"""Build the single-header web UI embedded by the ESP8266 firmware."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "index.html"
CSS = ROOT / "style.css"
JS = ROOT / "script.js"
OUTPUT = ROOT / "server" / "file1.h"


def main() -> None:
    html = INDEX.read_text(encoding="utf-8")
    css = CSS.read_text(encoding="utf-8")
    js = JS.read_text(encoding="utf-8")

    html = re.sub(r'\s*<link rel="manifest"[^>]*>', "", html)
    html = re.sub(r'\s*<link rel="icon"[^>]*>', "", html)
    html = html.replace('<link rel="stylesheet" href="style.css">', f"<style>\n{css}\n</style>")
    html = html.replace('<script src="script.js" defer></script>', "")
    html = html.replace("</body>", f"<script>\n{js}\n</script>\n</body>")
    html = html.replace(
        'src="assets/fun-with-binary-icon.svg"',
        'src="data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 64 64\'%3E%3Crect width=\'64\' height=\'64\' rx=\'15\' fill=\'%2306121f\'/%3E%3Ctext x=\'32\' y=\'41\' text-anchor=\'middle\' font-family=\'monospace\' font-size=\'25\' font-weight=\'700\' fill=\'%2375edff\'%3E01%3C/text%3E%3C/svg%3E',
    )

    # Avoid terminating the C++ raw string literal by accident.
    html = html.replace(')FWB"', ')F_W_B"')
    header = (
        "#pragma once\n\n"
        "// Generated by tools/build-embedded.py. Do not edit directly.\n"
        "const char file1[] PROGMEM = R\"FWB("
        + html
        + ")FWB\";\n"
    )
    OUTPUT.write_text(header, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({OUTPUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
